In [1]:
#16. Write a NumPy program to create a 3x3x3 array filled with arbitrary     values.

In [2]:
import numpy as np

In [17]:
arr= np.random.randn(3,3,3)
print(arr)

[[[-0.32340855 -1.33379288  0.02811627]
  [-1.06648644  0.19975625  0.99390563]
  [ 2.51452909 -0.13535941  1.09266752]]

 [[-0.26812519 -1.21134379  0.20259073]
  [-1.63694294  0.35546063  1.33775761]
  [ 0.57888694  0.53827934  0.13145643]]

 [[ 0.5454402  -0.04124936 -0.52642083]
  [-0.35708823  1.10456475  0.59674028]
  [ 0.37277114 -1.93850412  1.55723738]]]
