In [2]:
#11. Create any two arrays & perform various mathematical operations.
#    i.e. Addition, Substraction, Multiplication, Divide.

In [4]:
import numpy as np

In [5]:
arr1=np.array([20,40,60,80,100])
arr2=np.array([10,20,30,40,50])

In [6]:
print(arr1 + arr2)

[ 30  60  90 120 150]


In [7]:
print(arr1 - arr2)

[10 20 30 40 50]


In [8]:
print(arr1 * arr2)

[ 200  800 1800 3200 5000]


In [9]:
print(arr1 / arr2)

[2. 2. 2. 2. 2.]
