In [1]:
#19. Write a NumPy program to create a 3x3 matrix with values ranging from 2     to 10.

In [2]:
import numpy as np

In [7]:
matrix = np.random.randint(2,10,9).reshape(3,3)
print(matrix)

[[9 2 9]
 [3 2 5]
 [5 3 9]]
