In [1]:
#17. Write a NumPy program to create a 2x3x4 array filled with arbitrary     values.

In [2]:
import numpy as np

In [3]:
arr = np.random.rand(2,3,3)
print(arr)

[[[0.33062012 0.8822442  0.11850956]
  [0.09226862 0.46152851 0.90168468]
  [0.15048154 0.19593655 0.86474218]]

 [[0.75962428 0.93838652 0.74162944]
  [0.62618317 0.12683353 0.59485853]
  [0.97952298 0.29034754 0.65709909]]]
