In [1]:
# 3.  Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.

In [2]:
import numpy as np

In [5]:
arr0 = np.zeros(10)
print(arr0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
arr1 = np.ones(10)
print(arr1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
arr5 = np.ones(10)*5
print(arr5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [16]:
arr10 = np.ones(10)*10
print(arr10)

[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


In [17]:
arr20 = np.ones(10)*20
print(arr20)

[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]


[[ 1  2  3  4]
 [ 8  9 10 12]]
NDIM = 2
Size = 8
