In [15]:
#14. Write a NumPy program to find the number of rows and columns in a given     matrix.

In [16]:
import numpy as np

In [17]:
arr = np.random.randint(0,9,9)
print(arr)

[7 6 7 6 5 8 0 4 5]


In [18]:
arr1 = arr.reshape(3,3)
print(arr1)

[[7 6 7]
 [6 5 8]
 [0 4 5]]


In [19]:
nr,nc = arr1.shape
print(arr1.shape)

(3, 3)


In [20]:
print("Number of Rows: ",nr)
print("Number of Rows: ",nr)

Number of Rows:  3
Number of Rows:  3
