In [1]:
#12. Write a NumPy program to create a 3x4 matrix filled with values from 10     to 21.

In [2]:
import numpy as np

In [30]:
#arr = np.random.randint(10,21,12)
#print(arr)

#arr1=arr.reshape(3,4)
#print(arr1)

arr = np.random.randint(10,21,12).reshape(3,4)
print(arr)

[[15 14 19 13]
 [20 19 20 18]
 [10 15 15 18]]
